spring:
  main.web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: user
    password: psw
  sql:
    init:
      mode: always

server:
  port: 8080

ignite:
  addresses: localhost:10800
  cache-name: partner_cache

warmup:
  enabled: false
  records: 1_500_000
  batch-size: 2_000
  block-until-done: true
